import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/layouts/Navbar/Navbar'
import Sidebar from '@/layouts/Sidebar/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Messenger App',
  description: 'Generated by MohamedAli Aissaoui & Bilel Salems',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-screen overflow-hidden`} >
        <Navbar />
        <section className='flex w-full' >
          <Sidebar />
          <section className='w-full' >
            {children}
          </section>
        </section>
      </body>
    </html>
  )
}
